@ECHO OFF
"E:\ATMEL\AvrAssembler2\avrasm2.exe" -S "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\labels.tmp" -fI -W+ie -o "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\SIPM_CONTR_D.hex" -d "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\SIPM_CONTR_D.obj" -e "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\SIPM_CONTR_D.eep" -m "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\SIPM_CONTR_D.map" "F:\AVR_PRJ\SIPM_CONTR\SIPM_D\SIPM_CONTR_D.asm"
