@ECHO OFF
"E:\ATMEL\AvrAssembler2\avrasm2.exe" -S "F:\AVR_PRJ\SIPM_CONTR\labels.tmp" -fI -W+ie -o "F:\AVR_PRJ\SIPM_CONTR\SIPM_CONTR.hex" -d "F:\AVR_PRJ\SIPM_CONTR\SIPM_CONTR.obj" -e "F:\AVR_PRJ\SIPM_CONTR\SIPM_CONTR.eep" -m "F:\AVR_PRJ\SIPM_CONTR\SIPM_CONTR.map" "F:\AVR_PRJ\SIPM_CONTR\SIPM_CONTR_m48.asm"
